//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentLife
{
    using System;
    using System.Collections.Generic;
    
    public partial class hap
    {
        public int id { get; set; }
        public string name { get; set; }
        public System.DateTime hapDate { get; set; }
        public System.TimeSpan startTime { get; set; }
        public Nullable<System.TimeSpan> endTime { get; set; }
        public string hapDescription { get; set; }
        public Nullable<int> cost { get; set; }
        public string orgName { get; set; }
    
        public virtual organization organization { get; set; }
    }
}
