//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentLife
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class StudentLifeEntities : DbContext
    {
        public StudentLifeEntities()
            : base("name=StudentLifeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<hap> haps { get; set; }
        public virtual DbSet<organization> organizations { get; set; }
    
        public virtual ObjectResult<usp_FindAllEvents_Result> usp_FindAllEvents()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_FindAllEvents_Result>("usp_FindAllEvents");
        }
    
        public virtual ObjectResult<usp_FindEventByOrganization_Result> usp_FindEventByOrganization(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_FindEventByOrganization_Result>("usp_FindEventByOrganization", idParameter);
        }
    
        public virtual ObjectResult<usp_GetOrganizationById_Result> usp_GetOrganizationById(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetOrganizationById_Result>("usp_GetOrganizationById", idParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> usp_OrgLogin(Nullable<int> id, string passphrase)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var passphraseParameter = passphrase != null ?
                new ObjectParameter("passphrase", passphrase) :
                new ObjectParameter("passphrase", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("usp_OrgLogin", idParameter, passphraseParameter);
        }
    }
}
